max_windows = 13

name_max_length = 30
name_padding = 1

separator_string = ""
empty_desktop_string = ""

active_window_left_click = "raise_or_minimize"
active_window_middle_click = "floating"
active_window_right_click = "close"
active_window_scroll_up = ""
active_window_scroll_down = ""

inactive_window_left_click = "raise_or_minimize"
inactive_window_middle_click = "floating"
inactive_window_right_click = "close"
inactive_window_scroll_up = ""
inactive_window_scroll_down = ""

hidden_window_left_click = "raise_or_minimize"
hidden_window_middle_click = "floating"
hidden_window_right_click = "close"
hidden_window_scroll_up = ""
hidden_window_scroll_down = ""

active_window_fg_color = ""
active_window_bg_color = "#292e42"
active_window_ul_color = "#a9b1d6"

inactive_window_fg_color = ""
inactive_window_bg_color = ""
inactive_window_ul_color = ""

hidden_window_fg_color = "#3b4261"
hidden_window_bg_color = ""
hidden_window_ul_color = ""

separator_fg_color = "#7dcfff"
separator_bg_color = ""
separator_ul_color = ""

empty_desktop_fg_color = ""
empty_desktop_bg_color = ""
empty_desktop_ul_color = ""

[flags]
sticky = ""
locked = ""
private = ""
marked = ""

ignored_classes = [
    # "foo",
    # "bar"
]

[window_nicknames]
Code = " VSCode"
TelegramDesktop = " Telegram"
Slack = " Slack"
Alacritty = " Alacritty"
Google-chrome = " Chrome"
firefoxdeveloperedition = " Firefox Dev"
jetbrains-goland = " Goland"
jetbrains-phpstorm = " PHPStorm"
discord = " Discord"
Thunar = " Thunar"
com-jetbrains-toolbox-entry-ToolboxEntry = "Jetbrains Toolbox"
jetbrains-webstorm = "WebStorm"

